### ISSUE TITLE
Type 'Lambda Log | Lambda Log' is not assignable to type 'Lambda Log'.

### ISSUE THREAD

**Issue by rahul1500** [VoxaAI/voxa#265]
./run-ci.sh
+ NODE_ENV=development
+ yarn install --frozen-lockfile
yarn install v1.17.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.66s.
+ NODE_ENV=development
+ yarn run lint
yarn run v1.17.3
$ tslint --config tslint.json --project tsconfig.json
✨  Done in 5.51s.
+ NODE_ENV=development
+ yarn run test-ci
yarn run v1.17.3
$ NODE_ENV=local.example nyc mocha --reporter mocha-jenkins-reporter test test/*.spec.* test/**/*.spec.*

/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:226
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/services/Storage.ts:18:5 - error TS2322: Type 'LambdaLog | LambdaLog' is not assignable to type 'LambdaLog'.
  Type 'import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/voxa/node_modules/@types/lambda-log/index").LambdaLog' is not assignable to type 'import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/@types/lambda-log/index").LambdaLog'.
    Types of property 'options' are incompatible.
      Type 'import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/voxa/node_modules/@types/lambda-log/index").LambdaLogOptions' is not assignable to type 'import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/@types/lambda-log/index").LambdaLogOptions'.
        Types of property 'dynamicMeta' are incompatible.
          Type '((message: import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/voxa/node_modules/@types/lambda-log/index").LogMessage) => any) | undefined' is not assignable to type '((message: import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/@types/lambda-log/index").LogMessage) => any) | undefined'.
            Type '(message: import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/voxa/node_modules/@types/lambda-log/index").LogMessage) => any' is not assignable to type '(message: import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/@types/lambda-log/index").LogMessage) => any'.
              Types of parameters 'message' and 'message' are incompatible.
                Type 'import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/@types/lambda-log/index").LogMessage' is not assignable to type 'import("/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/voxa/node_modules/@types/lambda-log/index").LogMessage'.
                  Types of property 'toJSON' are incompatible.
                    Type '(format?: number | undefined) => string' is not assignable to type '(format?: boolean | undefined) => string'.
                      Types of parameters 'format' and 'format' are incompatible.
                        Type 'boolean | undefined' is not assignable to type 'number | undefined'.
                          Type 'false' is not assignable to type 'number | undefined'.

18     this.log = event ? event.log : new LambdaLog();
       ~~~~~~~~

    at createTSError (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:226:12)
    at getOutput (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:335:40)
    at Object.compile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:368:11)
    at Module.m._compile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:414:43)
    at Module.replacementCompile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at /Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/src/services/User.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:414:23)
    at Module.replacementCompile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at /Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/src/app/index.ts:20:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:414:23)
    at Module.replacementCompile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at /Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/test/tear-up-helpers.ts:13:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:414:23)
    at Module.replacementCompile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at /Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/test/alexa/launch.spec.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:414:23)
    at Module.replacementCompile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at /Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at runMain (/Users/rahul.patwa/.node-spawn-wrap-93339-984d468c4e43/node:68:10)
    at Function.<anonymous> (/Users/rahul.patwa/.node-spawn-wrap-93339-984d468c4e43/node:171:5)
    at Object.<anonymous> (/Users/rahul.patwa/voxa-starterkit-qa-isobar/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at /Users/rahul.patwa/.node-spawn-wrap-93339-984d468c4e43/node:178:8
    at Object.<anonymous> (/Users/rahul.patwa/.node-spawn-wrap-93339-984d468c4e43/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    92.86 |       75 |        0 |      100 |                   |
 index.js |    92.86 |       75 |        0 |      100 |                 7 |
----------|----------|----------|----------|----------|-------------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by spatical** [comment]
@rahul1500 please check out the latest code that is now updated in the bitbucket code.   Thanks!
